"""empty message

Revision ID: a9a91df97416
Revises: 3db26d4e83be
Create Date: 2023-10-02 11:05:39.879917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9a91df97416'
down_revision = '3db26d4e83be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vyrobce',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vyrobce_vozidla', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('typ_vozidla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('typ_vozidla', sa.String(length=30), nullable=True),
    sa.Column('vyrobce_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vyrobce_id'], ['vyrobce.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('typ_vozidla')
    op.drop_table('vyrobce')
    # ### end Alembic commands ###
